name: e2e Test

on:
  pull_request:
    branches:
      - main

jobs:
  e2e-test:
    name: e2e Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make xorg libx11-dev libxext-dev zlib1g-dev libbsd-dev xvfb

      - name: Compile libft
        run: |
          make -C libft
        
      - name: Compile cub3D
        run: |
          make

      - name: Verify binary architecture
        run: |
          file ./cub3D

      - name: Run Bash Script with Xvfb
        env:
          DISPLAY: ":99"
        run: |
          chmod +x ./test/e2e/runner.sh
          xvfb-run -a ./test/e2e/runner.sh