name: Norm Check

on:
  pull_request:
    branches:
      - develop

jobs:
  norm-check:
    name: Norm Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Norminette
        run: |
          python3 -m pip install --upgrade pip
          pip install norminette==3.3.51

      - name: Run Norminette
        run: |
          norminette .
        continue-on-error: false

      - name: Show Norminette Results
        if: failure()
        run: |
          echo "Norminette check failed. Please fix the issues above."